
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author leona
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtBemVindo = new javax.swing.JLabel();
        lblTipoEquipamento = new javax.swing.JLabel();
        cmbTipoEquipamento = new javax.swing.JComboBox<>();
        lblModelo = new javax.swing.JLabel();
        lblSerial = new javax.swing.JLabel();
        lblFabricante = new javax.swing.JLabel();
        lblDataCadastro = new javax.swing.JLabel();
        txtDataCadastro = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtSerial = new javax.swing.JTextField();
        txtFabricante = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();
        btnCadastrarEquipamento = new javax.swing.JButton();
        btnEquipamentoCadastrado = new javax.swing.JButton();
        cmbStatus = new javax.swing.JComboBox<>();
        btnLimpar = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Inicial");
        getContentPane().setLayout(null);

        txtBemVindo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtBemVindo.setText("Bem vindo(a) Admin");
        getContentPane().add(txtBemVindo);
        txtBemVindo.setBounds(7, 5, 320, 14);

        lblTipoEquipamento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblTipoEquipamento.setText("Tipo de equipamento");
        getContentPane().add(lblTipoEquipamento);
        lblTipoEquipamento.setBounds(35, 38, 130, 30);

        cmbTipoEquipamento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cmbTipoEquipamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "monitores", "Gabinetes", "HD's", "Teclados", "Mouses" }));
        cmbTipoEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoEquipamentoActionPerformed(evt);
            }
        });
        getContentPane().add(cmbTipoEquipamento);
        cmbTipoEquipamento.setBounds(180, 40, 100, 23);

        lblModelo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblModelo.setText("Modelo");
        getContentPane().add(lblModelo);
        lblModelo.setBounds(35, 75, 130, 25);

        lblSerial.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblSerial.setText("Serial / Identificação");
        getContentPane().add(lblSerial);
        lblSerial.setBounds(35, 114, 130, 25);

        lblFabricante.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblFabricante.setText("Fabricante");
        getContentPane().add(lblFabricante);
        lblFabricante.setBounds(35, 151, 130, 25);

        lblDataCadastro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDataCadastro.setText("Data de cadastro");
        getContentPane().add(lblDataCadastro);
        lblDataCadastro.setBounds(35, 188, 130, 25);

        txtDataCadastro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(txtDataCadastro);
        txtDataCadastro.setBounds(175, 188, 170, 25);

        txtModelo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(txtModelo);
        txtModelo.setBounds(175, 74, 170, 25);

        txtSerial.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(txtSerial);
        txtSerial.setBounds(175, 112, 170, 25);

        txtFabricante.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(txtFabricante);
        txtFabricante.setBounds(175, 151, 170, 25);

        lblStatus.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblStatus.setText("Status (Manutenção / Em uso)");
        getContentPane().add(lblStatus);
        lblStatus.setBounds(35, 225, 170, 35);

        btnCadastrarEquipamento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCadastrarEquipamento.setText(" Cadastrar Equipamento");
        btnCadastrarEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarEquipamentoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrarEquipamento);
        btnCadastrarEquipamento.setBounds(350, 265, 170, 35);

        btnEquipamentoCadastrado.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnEquipamentoCadastrado.setText("Equipamentos cadastrados");
        btnEquipamentoCadastrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEquipamentoCadastradoActionPerformed(evt);
            }
        });
        getContentPane().add(btnEquipamentoCadastrado);
        btnEquipamentoCadastrado.setBounds(350, 20, 187, 40);

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manutenção", "em uso" }));
        cmbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStatusActionPerformed(evt);
            }
        });
        getContentPane().add(cmbStatus);
        cmbStatus.setBounds(215, 230, 100, 24);

        btnLimpar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnLimpar.setText("Limpar");
        getContentPane().add(btnLimpar);
        btnLimpar.setBounds(35, 265, 100, 35);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/aaa.png"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(-6, -5, 550, 330);

        setSize(new java.awt.Dimension(558, 358));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTipoEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoEquipamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoEquipamentoActionPerformed

    private void btnCadastrarEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarEquipamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastrarEquipamentoActionPerformed

    private void cmbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbStatusActionPerformed

    private void btnEquipamentoCadastradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEquipamentoCadastradoActionPerformed
        TelaCadastrados tela;
        dispose();
        tela = new TelaCadastrados();
        tela.setVisible(true);
    }//GEN-LAST:event_btnEquipamentoCadastradoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton btnCadastrarEquipamento;
    private javax.swing.JButton btnEquipamentoCadastrado;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JComboBox<String> cmbTipoEquipamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDataCadastro;
    private javax.swing.JLabel lblFabricante;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblSerial;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTipoEquipamento;
    private javax.swing.JLabel txtBemVindo;
    private javax.swing.JTextField txtDataCadastro;
    private javax.swing.JTextField txtFabricante;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtSerial;
    // End of variables declaration//GEN-END:variables
}
