/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author leona
 */
public class TelaCadastrados extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastrados
     */
    public TelaCadastrados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lblSelecEquip = new javax.swing.JLabel();
        cmbEquipamentoSelec = new javax.swing.JComboBox<>();
        lblModelo = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblSerial = new javax.swing.JLabel();
        lblFabricante = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        btnAlterar = new javax.swing.JButton();
        imgEquip = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        txtSerial = new javax.swing.JTextField();
        txtFabricante = new javax.swing.JTextField();
        txtDataCadastro = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lblSelecEquip.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblSelecEquip.setText("Selecione o equipamento");
        lblSelecEquip.setPreferredSize(new java.awt.Dimension(141, 20));
        getContentPane().add(lblSelecEquip);
        lblSelecEquip.setBounds(12, 26, 141, 20);

        cmbEquipamentoSelec.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cmbEquipamentoSelec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "monitores", "Gabinetes", "HD's", "Teclados", "Mouses" }));
        cmbEquipamentoSelec.setPreferredSize(new java.awt.Dimension(141, 20));
        getContentPane().add(cmbEquipamentoSelec);
        cmbEquipamentoSelec.setBounds(165, 26, 141, 20);

        lblModelo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblModelo.setText("modelo:");
        lblModelo.setPreferredSize(new java.awt.Dimension(141, 20));
        getContentPane().add(lblModelo);
        lblModelo.setBounds(12, 65, 141, 20);

        lblData.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblData.setText("Data de cadastro:");
        lblData.setPreferredSize(new java.awt.Dimension(141, 20));
        getContentPane().add(lblData);
        lblData.setBounds(12, 180, 141, 20);

        lblSerial.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblSerial.setText("Serial / Identificação:");
        lblSerial.setPreferredSize(new java.awt.Dimension(141, 20));
        getContentPane().add(lblSerial);
        lblSerial.setBounds(12, 104, 141, 20);

        lblFabricante.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblFabricante.setText("Fabricante:");
        lblFabricante.setPreferredSize(new java.awt.Dimension(141, 20));
        getContentPane().add(lblFabricante);
        lblFabricante.setBounds(12, 142, 141, 20);

        lblStatus.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblStatus.setText("Status:");
        lblStatus.setPreferredSize(new java.awt.Dimension(141, 20));
        getContentPane().add(lblStatus);
        lblStatus.setBounds(12, 218, 141, 20);

        btnAlterar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnAlterar.setText("Alterar dados");
        btnAlterar.setPreferredSize(new java.awt.Dimension(169, 24));
        getContentPane().add(btnAlterar);
        btnAlterar.setBounds(432, 270, 120, 34);

        imgEquip.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        imgEquip.setText("*Foto do equipamento*");
        imgEquip.setPreferredSize(new java.awt.Dimension(141, 20));
        getContentPane().add(imgEquip);
        imgEquip.setBounds(407, 142, 141, 20);

        txtModelo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(txtModelo);
        txtModelo.setBounds(165, 65, 140, 25);

        txtSerial.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(txtSerial);
        txtSerial.setBounds(164, 104, 140, 25);

        txtFabricante.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(txtFabricante);
        txtFabricante.setBounds(164, 142, 140, 25);

        txtDataCadastro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(txtDataCadastro);
        txtDataCadastro.setBounds(164, 180, 140, 25);

        txtStatus.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(txtStatus);
        txtStatus.setBounds(165, 218, 140, 25);

        btnSalvar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnSalvar.setText("Salvar");
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(12, 270, 120, 34);

        btnExcluir.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnExcluir.setText("Excluir");
        getContentPane().add(btnExcluir);
        btnExcluir.setBounds(152, 270, 120, 34);

        btnLimpar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnLimpar.setText("Limpar");
        getContentPane().add(btnLimpar);
        btnLimpar.setBounds(292, 270, 120, 34);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/aaa.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 620, 330);

        setSize(new java.awt.Dimension(626, 362));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastrados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmbEquipamentoSelec;
    private javax.swing.JLabel imgEquip;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblFabricante;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblSelecEquip;
    private javax.swing.JLabel lblSerial;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTextField txtDataCadastro;
    private javax.swing.JTextField txtFabricante;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtSerial;
    private javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables
}
