/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author leona
 */
public class AlunosMedia extends javax.swing.JFrame {

    /**
     * Creates new form AlunosMedia
     */
    public AlunosMedia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblnomealuno = new javax.swing.JLabel();
        txtnomealuno = new javax.swing.JTextField();
        lblra = new javax.swing.JLabel();
        txtra = new javax.swing.JTextField();
        lbldisciplina = new javax.swing.JLabel();
        txtdisciplina = new javax.swing.JTextField();
        lblav1 = new javax.swing.JLabel();
        lblav2 = new javax.swing.JLabel();
        lbltrab = new javax.swing.JLabel();
        txtav1 = new javax.swing.JTextField();
        txttrab = new javax.swing.JTextField();
        txtav2 = new javax.swing.JTextField();
        btnmedia = new javax.swing.JButton();
        txtmedia = new javax.swing.JTextField();
        lblmsg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle de média de alunos");

        lblnomealuno.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblnomealuno.setText("Nome do Aluno");

        txtnomealuno.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        lblra.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblra.setText("RA do Aluno");

        txtra.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        lbldisciplina.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbldisciplina.setText("Disciplina");

        txtdisciplina.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        lblav1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblav1.setText("AV1");

        lblav2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblav2.setText("AV2");

        lbltrab.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbltrab.setText("Trabalho");

        txtav1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txttrab.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtav2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        btnmedia.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnmedia.setText("Calcular Média");
        btnmedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmediaActionPerformed(evt);
            }
        });

        txtmedia.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        lblmsg.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblav2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtav2))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lbltrab, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblav1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbldisciplina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblnomealuno, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtnomealuno)
                                .addComponent(txtra)
                                .addComponent(txtdisciplina)
                                .addComponent(txtav1)
                                .addComponent(txttrab, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnmedia)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtmedia, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)))
                    .addComponent(lblmsg, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnomealuno, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnomealuno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblra)
                    .addComponent(txtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldisciplina)
                    .addComponent(txtdisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblav1)
                    .addComponent(txtav1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltrab)
                    .addComponent(txttrab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblav2)
                    .addComponent(txtav2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnmedia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtmedia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblmsg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(452, 417));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnmediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmediaActionPerformed
        
        String nome;
        double av1, trabalho, av2, media;
        
        nome = lblnomealuno.getText();
        av1 = Double.parseDouble (txtav1.getText());
        trabalho = Double.parseDouble (txttrab.getText());
        av2 = Double.parseDouble (txtav2.getText());
        media = (av1 + trabalho + av2) / 3;
        txtmedia.setText(String.valueOf (media));
        if (media < 6) {
            lblmsg.setText(nome + " você foi reprovado(a) com a média " + media);
        } else {
            lblmsg.setText (nome + " você foi aprovado(a) com a média " + media);
        }
        
    }//GEN-LAST:event_btnmediaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlunosMedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlunosMedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlunosMedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlunosMedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlunosMedia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnmedia;
    private javax.swing.JLabel lblav1;
    private javax.swing.JLabel lblav2;
    private javax.swing.JLabel lbldisciplina;
    private javax.swing.JLabel lblmsg;
    private javax.swing.JLabel lblnomealuno;
    private javax.swing.JLabel lblra;
    private javax.swing.JLabel lbltrab;
    private javax.swing.JTextField txtav1;
    private javax.swing.JTextField txtav2;
    private javax.swing.JTextField txtdisciplina;
    private javax.swing.JTextField txtmedia;
    private javax.swing.JTextField txtnomealuno;
    private javax.swing.JTextField txtra;
    private javax.swing.JTextField txttrab;
    // End of variables declaration//GEN-END:variables
}
