/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author leona
 */
public class TelaCadastrados extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastrados
     */
    public TelaCadastrados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSelecEquip = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        lblAparMod = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblAparData = new javax.swing.JLabel();
        lblSerial = new javax.swing.JLabel();
        lblAparSerial = new javax.swing.JLabel();
        lblFabricante = new javax.swing.JLabel();
        lblAparFab = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblAparStat = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        imgEquip = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lblSelecEquip.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblSelecEquip.setText("Selecione o equipamento");
        lblSelecEquip.setPreferredSize(new java.awt.Dimension(141, 20));
        getContentPane().add(lblSelecEquip);
        lblSelecEquip.setBounds(12, 26, 141, 20);

        jComboBox1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "monitores", "Gabinetes", "HD's", "Teclados", "Mouses" }));
        jComboBox1.setPreferredSize(new java.awt.Dimension(141, 20));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(165, 26, 141, 20);

        lblAparMod.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblAparMod.setText("*aparecer o modelo aqui*");
        lblAparMod.setPreferredSize(new java.awt.Dimension(141, 20));
        getContentPane().add(lblAparMod);
        lblAparMod.setBounds(165, 64, 141, 22);

        lblModelo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblModelo.setText("modelo:");
        lblModelo.setPreferredSize(new java.awt.Dimension(141, 20));
        getContentPane().add(lblModelo);
        lblModelo.setBounds(12, 65, 141, 20);

        lblData.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblData.setText("Data de cadastro:");
        lblData.setPreferredSize(new java.awt.Dimension(141, 20));
        getContentPane().add(lblData);
        lblData.setBounds(12, 180, 141, 20);

        lblAparData.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblAparData.setText("*Data aqui*");
        lblAparData.setPreferredSize(new java.awt.Dimension(141, 20));
        getContentPane().add(lblAparData);
        lblAparData.setBounds(165, 180, 141, 20);

        lblSerial.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblSerial.setText("Serial / Identificação:");
        lblSerial.setPreferredSize(new java.awt.Dimension(141, 20));
        getContentPane().add(lblSerial);
        lblSerial.setBounds(12, 104, 141, 20);

        lblAparSerial.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblAparSerial.setText("*Serial*");
        lblAparSerial.setPreferredSize(new java.awt.Dimension(141, 20));
        getContentPane().add(lblAparSerial);
        lblAparSerial.setBounds(165, 104, 141, 20);

        lblFabricante.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblFabricante.setText("Fabricante:");
        lblFabricante.setPreferredSize(new java.awt.Dimension(141, 20));
        getContentPane().add(lblFabricante);
        lblFabricante.setBounds(12, 142, 141, 20);

        lblAparFab.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblAparFab.setText("*Fabricante*");
        lblAparFab.setPreferredSize(new java.awt.Dimension(141, 20));
        getContentPane().add(lblAparFab);
        lblAparFab.setBounds(165, 142, 141, 20);

        lblStatus.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblStatus.setText("Status:");
        lblStatus.setPreferredSize(new java.awt.Dimension(141, 20));
        getContentPane().add(lblStatus);
        lblStatus.setBounds(12, 218, 141, 20);

        lblAparStat.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblAparStat.setText("*Manutenção / Em uso*");
        lblAparStat.setPreferredSize(new java.awt.Dimension(141, 20));
        getContentPane().add(lblAparStat);
        lblAparStat.setBounds(165, 218, 141, 20);

        jButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton1.setText("Alterar dados");
        jButton1.setPreferredSize(new java.awt.Dimension(169, 24));
        getContentPane().add(jButton1);
        jButton1.setBounds(407, 310, 169, 34);

        imgEquip.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        imgEquip.setText("*Foto do equipamento*");
        imgEquip.setPreferredSize(new java.awt.Dimension(141, 20));
        getContentPane().add(imgEquip);
        imgEquip.setBounds(407, 142, 141, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/aaa.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-6, -5, 620, 380);

        setSize(new java.awt.Dimension(626, 409));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastrados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgEquip;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAparData;
    private javax.swing.JLabel lblAparFab;
    private javax.swing.JLabel lblAparMod;
    private javax.swing.JLabel lblAparSerial;
    private javax.swing.JLabel lblAparStat;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblFabricante;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblSelecEquip;
    private javax.swing.JLabel lblSerial;
    private javax.swing.JLabel lblStatus;
    // End of variables declaration//GEN-END:variables
}
