/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author leona
 */
public class TelaConsultasClientes extends javax.swing.JFrame {

    /**
     * Creates new form TelaConsultasClientes
     */
    public TelaConsultasClientes() {
        initComponents();
        lblCidade.setVisible(false);
        txtCidade.setVisible(false);
        lblMinimo.setVisible(false);
        txtMinimo.setVisible(false);
        lblMaximo.setVisible(false);
        txtMaximo.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTiposConsultas = new javax.swing.JLabel();
        cmbTiposConsultas = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblConsultas = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        lblCidade = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        btnLimpar = new javax.swing.JButton();
        lblMinimo = new javax.swing.JLabel();
        txtMinimo = new javax.swing.JTextField();
        lblMaximo = new javax.swing.JLabel();
        txtMaximo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTiposConsultas.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblTiposConsultas.setText("Escolha o tipo de consulta");

        cmbTiposConsultas.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cmbTiposConsultas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Consulta geral de clientes", "Consulta por cidade", "Consulta por renda", " " }));
        cmbTiposConsultas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTiposConsultasItemStateChanged(evt);
            }
        });
        cmbTiposConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTiposConsultasActionPerformed(evt);
            }
        });

        tblConsultas.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tblConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Cpf", "Endereço", "Telefone"
            }
        ));
        jScrollPane1.setViewportView(tblConsultas);

        btnBuscar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblCidade.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblCidade.setText("Cidade");

        txtCidade.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        btnLimpar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        lblMinimo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblMinimo.setText("Minimo");

        txtMinimo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtMinimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMinimoActionPerformed(evt);
            }
        });

        lblMaximo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblMaximo.setText("maximo");

        txtMaximo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblMaximo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMaximo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTiposConsultas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbTiposConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscar)
                    .addComponent(btnLimpar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTiposConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTiposConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(509, 422));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        Limpar();  
        if (cmbTiposConsultas.getSelectedItem().toString().equals("Consulta por cidade")){
            lblCidade.setVisible(true);
            txtCidade.setVisible(true);
        } else if (cmbTiposConsultas.getSelectedItem().toString().equals("Consulta por renda")){ 
           lblMinimo.setVisible(true);
           txtMinimo.setVisible(true);
           lblMaximo.setVisible(true);
           txtMaximo.setVisible(true);
        }else {
           lblCidade.setVisible(false);
           txtCidade.setVisible(false);
           lblMinimo.setVisible(false);
           txtMinimo.setVisible(false);
           lblMaximo.setVisible(false);
           txtMaximo.setVisible(false);
        }
        try {
            //1) Conectar no BD
            Connection con;
            PreparedStatement st;
            ResultSet rs;
            String combo;
            DefaultTableModel tblClientes;
            
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/acesso", "root", "987543@#Leo");
            
            //2) Fazer a busca do cpf digitado no campo
            //txtCpf, na tabela cliente
            combo = cmbTiposConsultas.getSelectedItem().toString();
            if(combo.equalsIgnoreCase("Consulta geral de clientes")) {
                st = con.prepareStatement("SELECT * FROM cliente");
                rs = st.executeQuery();
                tblClientes = (DefaultTableModel) tblConsultas.getModel();
                while(rs.next()) { //Enquanto tiver linha de cliente no rs
                    Object[] dados = {rs.getString("nome"), rs.getString("cpf"), rs.getString("endereco"), rs.getString("telefone")};
                    tblClientes.addRow(dados);
                }
            }else if(combo.equalsIgnoreCase("Consulta por cidade")) {
                st = con.prepareStatement("SELECT * FROM cliente WHERE cidade = ?");
                st.setString(1, txtCidade.getText());
                rs = st.executeQuery();
                tblClientes = (DefaultTableModel) tblConsultas.getModel();
                while(rs.next()) { //Enquanto tiver linha de cliente no rs
                    Object[] dados = {rs.getString("nome"), rs.getString("cpf"), rs.getString("endereco"), rs.getString("telefone")};
                    tblClientes.addRow(dados);
                }
            } else if (combo.equalsIgnoreCase("Consulta por renda")) {
                st = con.prepareStatement("SELECT * FROM cliente WHERE renda BETWEEN ? AND ?");
                st.setDouble(1, Double.parseDouble(txtMinimo.getText()));
                st.setDouble(2, Double.parseDouble(txtMaximo.getText()));
                rs = st.executeQuery();
                tblClientes = (DefaultTableModel) tblConsultas.getModel();
                while (rs.next()) { // Enquanto tiver linnha de cliente no rs
                    Object[] dados = {
                        rs.getString("cpf"),
                        rs.getString("nome"),
                        rs.getString("telefone"),
                        rs.getString("renda")};
                    tblClientes.addRow(dados);
                }

            }
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao tentar acessar a base de dados, entre em contato com o administrador e informe o erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        Limpar();
    }//GEN-LAST:event_btnLimparActionPerformed

    public void Limpar(){
        DefaultTableModel tblClientes = (DefaultTableModel) tblConsultas.getModel();
        tblClientes.getDataVector().removeAllElements();
        tblClientes.fireTableDataChanged();
    }
    private void cmbTiposConsultasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTiposConsultasItemStateChanged
        
        if (cmbTiposConsultas.getSelectedItem().toString().equals("Consulta por cidade")) {
            lblCidade.setVisible(true);
            txtCidade.setVisible(true);
        } else if (cmbTiposConsultas.getSelectedItem().toString().equals("Consulta por renda")) {
            lblMinimo.setVisible(true);
            txtMinimo.setVisible(true);
            lblMaximo.setVisible(true);
            txtMaximo.setVisible(true);
        } else {
            lblCidade.setVisible(false);
            txtCidade.setVisible(false);
            lblMinimo.setVisible(false);
            txtMinimo.setVisible(false);
            lblMaximo.setVisible(false);
            txtMaximo.setVisible(false);
        }
    }//GEN-LAST:event_cmbTiposConsultasItemStateChanged

    private void txtMinimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMinimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMinimoActionPerformed

    private void cmbTiposConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTiposConsultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTiposConsultasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConsultasClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConsultasClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConsultasClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConsultasClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConsultasClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JComboBox<String> cmbTiposConsultas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblMaximo;
    private javax.swing.JLabel lblMinimo;
    private javax.swing.JLabel lblTiposConsultas;
    private javax.swing.JTable tblConsultas;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtMaximo;
    private javax.swing.JTextField txtMinimo;
    // End of variables declaration//GEN-END:variables
}
