/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

/**
 *
 * @author leona
 */
public class TelaMenu extends javax.swing.JFrame {

    /**
     * Creates new form TelaMenu
     */
    public TelaMenu() {
        initComponents();
    }

    public TelaMenu(String nome, String cargo) {
        initComponents();
        lblBV.setText("Bem-vindo(a) " + nome);
        if(cargo.equalsIgnoreCase("Estagiário")) {
            btnVendas.setEnabled(false);
            btnFuncionarios.setEnabled(false);
        } else if(cargo.equalsIgnoreCase("Vendedor")) {
            btnFuncionarios.setEnabled(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnClientes = new javax.swing.JButton();
        btnProdutos = new javax.swing.JButton();
        btnFuncionarios = new javax.swing.JButton();
        btnVendas = new javax.swing.JButton();
        lblBV = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnClientes.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnClientes.setText("Controle de clientes");
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        getContentPane().add(btnClientes);
        btnClientes.setBounds(20, 50, 180, 40);

        btnProdutos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnProdutos.setText("Controle de produtos");
        btnProdutos.setPreferredSize(new java.awt.Dimension(144, 24));
        getContentPane().add(btnProdutos);
        btnProdutos.setBounds(220, 50, 180, 40);

        btnFuncionarios.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnFuncionarios.setText("Controle de funcionários");
        btnFuncionarios.setPreferredSize(new java.awt.Dimension(144, 24));
        getContentPane().add(btnFuncionarios);
        btnFuncionarios.setBounds(20, 158, 180, 40);

        btnVendas.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnVendas.setText("Controle de vendas");
        btnVendas.setPreferredSize(new java.awt.Dimension(144, 24));
        getContentPane().add(btnVendas);
        btnVendas.setBounds(220, 158, 180, 40);

        lblBV.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(lblBV);
        lblBV.setBounds(20, 10, 380, 30);

        setSize(new java.awt.Dimension(452, 301));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        
        TelaClientes t;
        t = new TelaClientes();
        t.setVisible(true);
        
    }//GEN-LAST:event_btnClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnFuncionarios;
    private javax.swing.JButton btnProdutos;
    private javax.swing.JButton btnVendas;
    private javax.swing.JLabel lblBV;
    // End of variables declaration//GEN-END:variables
}
