/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.ResultSet;



/**
 *
 * @author leona
 */
public class TelaClientes extends javax.swing.JFrame {

    /**
     * Creates new form TelaClientes
     */
    public TelaClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblCpf = new javax.swing.JLabel();
        txtCpf = new javax.swing.JTextField();
        lblEndereco = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        lblBairro = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        lblCidade = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        lblTelefone = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        lblRenda = new javax.swing.JLabel();
        txtRenda = new javax.swing.JTextField();
        btnLimpar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnOutrasConsultas = new javax.swing.JButton();

        setTitle("Controle de clientes");
        getContentPane().setLayout(null);

        lblNome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblNome.setText("NOME");
        getContentPane().add(lblNome);
        lblNome.setBounds(10, 20, 50, 30);

        txtNome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomeFocusLost(evt);
            }
        });
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtNome);
        txtNome.setBounds(100, 20, 370, 30);

        lblCpf.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblCpf.setText("CPF");
        getContentPane().add(lblCpf);
        lblCpf.setBounds(10, 70, 50, 30);

        txtCpf.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCpfFocusLost(evt);
            }
        });
        txtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfActionPerformed(evt);
            }
        });
        getContentPane().add(txtCpf);
        txtCpf.setBounds(100, 70, 200, 30);

        lblEndereco.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblEndereco.setText("ENDEREÇO");
        getContentPane().add(lblEndereco);
        lblEndereco.setBounds(10, 120, 80, 30);

        txtEndereco.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(txtEndereco);
        txtEndereco.setBounds(100, 120, 370, 30);

        lblBairro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblBairro.setText("BAIRRO");
        getContentPane().add(lblBairro);
        lblBairro.setBounds(10, 170, 50, 30);

        txtBairro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(txtBairro);
        txtBairro.setBounds(100, 170, 360, 30);

        lblCidade.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblCidade.setText("CIDADE");
        getContentPane().add(lblCidade);
        lblCidade.setBounds(10, 220, 50, 30);

        txtCidade.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(txtCidade);
        txtCidade.setBounds(100, 220, 250, 30);

        lblTelefone.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblTelefone.setText("TELEFONE");
        getContentPane().add(lblTelefone);
        lblTelefone.setBounds(10, 270, 80, 30);

        txtTelefone.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(txtTelefone);
        txtTelefone.setBounds(100, 270, 200, 30);

        lblRenda.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblRenda.setText("RENDA");
        getContentPane().add(lblRenda);
        lblRenda.setBounds(10, 320, 50, 30);

        txtRenda.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(txtRenda);
        txtRenda.setBounds(100, 320, 250, 30);

        btnLimpar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar);
        btnLimpar.setBounds(410, 380, 90, 30);

        btnConsultar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar);
        btnConsultar.setBounds(110, 380, 90, 30);

        btnExcluir.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir);
        btnExcluir.setBounds(210, 380, 90, 30);

        btnAlterar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterar);
        btnAlterar.setBounds(310, 380, 90, 30);

        btnSalvar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(10, 380, 90, 30);

        btnOutrasConsultas.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnOutrasConsultas.setText("Mais consultas");
        btnOutrasConsultas.setToolTipText("");
        btnOutrasConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutrasConsultasActionPerformed(evt);
            }
        });
        getContentPane().add(btnOutrasConsultas);
        btnOutrasConsultas.setBounds(510, 380, 117, 30);

        setSize(new java.awt.Dimension(665, 476));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        Limpar();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        try {
            //1) Conectar no BD
            Connection con;
            PreparedStatement st;
            ResultSet rs;
            
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/acesso", "root", "987543@#Leo");
            
            //2) Fazer a busca do cpf digitado no campo
            //txtCpf, na tabela cliente
            st = con.prepareStatement("SELECT * FROM cliente WHERE cpf = ?");
            st.setString(1, txtCpf.getText());
            
            rs = st.executeQuery(); //Executa o SELECT na tabela do BD
            if(rs.next()) { //se encontrou o cpf no BD
                txtNome.setText(rs.getString("nome"));
                txtEndereco.setText(rs.getString("endereco"));
                txtBairro.setText(rs.getString("bairro"));
                txtCidade.setText(rs.getString("cidade"));
                txtTelefone.setText(rs.getString("telefone"));
                txtRenda.setText(rs.getString("renda"));
                btnExcluir.setEnabled(true);
                btnAlterar.setEnabled(true);
                txtCpf.setEditable(false);
            } else {
                JOptionPane.showMessageDialog(null, "CPF não encontrado");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao tentar acessar a base de dados, entre em contato com o administrador e informe o erro: " + ex.getMessage());
        }
        
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void Limpar() {
            
            txtCpf.setText("");
            txtNome.setText("");
            txtEndereco.setText("");
            txtBairro.setText("");
            txtCidade.setText("");
            txtTelefone.setText("");
            txtRenda.setText("");
            txtCpf.requestFocus();
            
    }
    
    
    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        try {
            //1) Conectar ao BD
            Connection con;
            PreparedStatement st;
            
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/acesso", "root", "987543@#Leo");
            
            //2) Executar o DELETE para excluir o cliente
            st = con.prepareStatement("DELETE FROM cliente WHERE cpf = ?");
            st.setString(1, txtCpf.getText());
            st.executeUpdate();
            
            //3) Dar feedback para o usuário
            JOptionPane.showMessageDialog(null, "cliente excluído com sucesso");
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao tentar acessar a base de dados, entre em contato com o administrador e informe o erro: " + ex.getMessage());
        }
            Limpar();
            btnExcluir.setEnabled(false);
            btnAlterar.setEnabled(false);
            txtCpf.setEditable(true);
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // Conectar no BD
        try {
            Connection con;
            PreparedStatement st;
            
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/acesso", "root", "987543@#Leo");
        
        // Executar a alteração(Update)
        st = con.prepareStatement("UPDATE cliente SET nome = ?, endereco = ?, bairro = ?, cidade = ?, telefone = ?, renda = ? WHERE cpf = ?");
        st.setString(1, txtNome.getText());
        st.setString(2, txtEndereco.getText());
        st.setString(3, txtBairro.getText());
        st.setString(4, txtCidade.getText());
        st.setString(5, txtTelefone.getText());
        st.setDouble(6, Double.parseDouble(txtRenda.getText()));
        st.setString(7, txtCpf.getText());
        st.executeUpdate();
        
        // Dar um feedback para o usuário
        JOptionPane.showMessageDialog(null, "Dados alterados com sucesso");
        Limpar();
        txtCpf.setEditable(true);
        btnExcluir.setEnabled(false);
        btnAlterar.setEnabled(false);
         } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao tentar alterar os dados, entre em contato com o administrador e informe o erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusLost
         try {
            //1) Conectar no BD
            Connection con;
            PreparedStatement st;
            ResultSet rs;
            
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/acesso", "root", "987543@#Leo");
            
            //2) Fazer a busca do nome digitado no campo
            //txtCpf, na tabela cliente
            st = con.prepareStatement("SELECT * FROM cliente WHERE nome = ?");
            st.setString(1, txtNome.getText());
            
            rs = st.executeQuery(); //Executa o SELECT na tabela do BD
            if(rs.next()) { //se encontrou o nome no BD
                JOptionPane.showMessageDialog(null, "Este nome ja está cadastrado");
                txtNome.requestFocus();
            }
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao tentar acessar a base de dados, entre em contato com o administrador e informe o erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_txtNomeFocusLost

    private void txtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfActionPerformed

    private void txtCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCpfFocusLost
        btnConsultar.doClick();
    }//GEN-LAST:event_txtCpfFocusLost

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
         try {
            // Conectar com o BD
            Connection con;
            PreparedStatement st;
            
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/acesso", "root", "987543@#Leo");

            st = con.prepareStatement("INSERT INTO cliente VALUES(?,?,?,?,?,?,?)");
            st.setString(1, txtCpf.getText());
            st.setString(2, txtNome.getText());
            st.setString(3, txtEndereco.getText());
            st.setString(4, txtBairro.getText());
            st.setString(5, txtCidade.getText());
            st.setString(6, txtTelefone.getText());
            st.setDouble(7, Double.parseDouble(txtRenda.getText()));            
            
            st.executeUpdate();
            JOptionPane.showMessageDialog(null,"Dados cadastrados com sucesso");

           Limpar();
            
       } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"Erro ao tentar salvar os dados. Entre em contato com o administrador do sistema e informe o erro  " + ex.getMessage());
        } catch (SQLException ex) {
           if (ex.getErrorCode()==1062){
             JOptionPane.showMessageDialog(null,"Este cliente já está cadastrado");
             txtCpf.requestFocus();
           }else{
             JOptionPane.showMessageDialog(null,"Erro ao tentar salvar os dados. Entre em contato com o administrador do sistema e informe o erro  " + ex.getErrorCode());
           }
        }

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnOutrasConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutrasConsultasActionPerformed
        TelaConsultasClientes tela;
        tela = new TelaConsultasClientes();
        tela.setVisible(true);
    }//GEN-LAST:event_btnOutrasConsultasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnOutrasConsultas;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblRenda;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtRenda;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
